### ISSUE TITLE
Missing adix/oats

### ISSUE THREAD

**Issue by Gruruya** [c-blake/adix#8]
`Error: adix/util/lfreq.nim(2, 64) Error: cannot open file: adix/oats`

Probably forgot to track it

**Comment by c-blake** [comment]
Sorry.  This is not even the first time the `git commit -a` in `bu/nrel.nim` has accidentally swept up changes that I had not yet decided to foist upon a package (& thus consumers).  I should probably fix that somehow.. probably just a more specific git commit.

Speaking of which, I should probably release a new adix version (and possibly bump consuming versions) in light of this mistake.
